# Ссылка на видео с уроком.
https://youtu.be/hO7b4yh-Qfs?si=6Q0lX4wplP7hIiE3
На этом уроке делается попытка создать базу данных на PostgreSQL,
создать структуру БД и сделать миграцию с СУБД.
На тайминге 23:02 автор в командной строке набирает:
alembic revision --autogenerate -m 'Database creation'
После этого у меня вылетает ошибка:
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc2 in position 61: invalid continuation byte

Полное сообщение:
(.venv) PS C:\Users\psk-a\PycharmProjects\FastAPI_project\Lesson_4> alembic revision --autogenerate -m 'Database creation'
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\psk-a\PycharmProjects\FastAPI_project\.venv\Scripts\alembic.exe\__main__.py", line 7, in <module>
  File "C:\Users\psk-a\PycharmProjects\FastAPI_project\.venv\Lib\site-packages\alembic\config.py", line 641, in main
    CommandLine(prog=prog).main(argv=argv)
  File "C:\Users\psk-a\PycharmProjects\FastAPI_project\.venv\Lib\site-packages\alembic\config.py", line 631, in main
    self.run_cmd(cfg, options)
  File "C:\Users\psk-a\PycharmProjects\FastAPI_project\.venv\Lib\site-packages\alembic\config.py", line 608, in run_cmd
    fn(
  File "C:\Users\psk-a\PycharmProjects\FastAPI_project\.venv\Lib\site-packages\alembic\command.py", line 236, in revision
    script_directory.run_env()
  File "C:\Users\psk-a\PycharmProjects\FastAPI_project\.venv\Lib\site-packages\alembic\script\base.py", line 583, in run_env
    util.load_python_file(self.dir, "env.py")
  File "C:\Users\psk-a\PycharmProjects\FastAPI_project\.venv\Lib\site-packages\alembic\util\pyfiles.py", line 95, in load_python_file
    module = load_module_py(module_id, path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\psk-a\PycharmProjects\FastAPI_project\.venv\Lib\site-packages\alembic\util\pyfiles.py", line 113, in load_module_py
    spec.loader.exec_module(module)  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\psk-a\PycharmProjects\FastAPI_project\Lesson_4\migrations\env.py", line 93, in <module>
    run_migrations_online()
  File "C:\Users\psk-a\PycharmProjects\FastAPI_project\Lesson_4\migrations\env.py", line 81, in run_migrations_online
    with connectable.connect() as connection:
         ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\psk-a\PycharmProjects\FastAPI_project\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 3258, in connect
    return self._connection_cls(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\psk-a\PycharmProjects\FastAPI_project\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 145, in __init__
    self._dbapi_connection = engine.raw_connection()
                             ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\psk-a\PycharmProjects\FastAPI_project\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 3282, in raw_connection
    return self.pool.connect()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\psk-a\PycharmProjects\FastAPI_project\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 449, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\psk-a\PycharmProjects\FastAPI_project\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 1263, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\psk-a\PycharmProjects\FastAPI_project\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 712, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "C:\Users\psk-a\PycharmProjects\FastAPI_project\.venv\Lib\site-packages\sqlalchemy\pool\impl.py", line 282, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\psk-a\PycharmProjects\FastAPI_project\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 390, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\psk-a\PycharmProjects\FastAPI_project\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 674, in __init__
    self.__connect()
  File "C:\Users\psk-a\PycharmProjects\FastAPI_project\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 900, in __connect
    with util.safe_reraise():
  File "C:\Users\psk-a\PycharmProjects\FastAPI_project\.venv\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "C:\Users\psk-a\PycharmProjects\FastAPI_project\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 896, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\psk-a\PycharmProjects\FastAPI_project\.venv\Lib\site-packages\sqlalchemy\engine\create.py", line 643, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\psk-a\PycharmProjects\FastAPI_project\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 616, in connect
    return self.loaded_dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\psk-a\PycharmProjects\FastAPI_project\.venv\Lib\site-packages\psycopg2\__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc2 in position 61: invalid continuation byte





